name: tslib
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=1.12.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # For GPU support - adjust based on your CUDA version
  - numpy>=1.19.2,<1.25.0  # Compatible with all methods
  - scipy>=1.6.1
  - pandas>=1.0.1
  - scikit-learn>=0.24.2
  - bottleneck>=1.3.2
  - statsmodels>=0.12.2
  - liac-arff  # For loading ARFF files (UEA datasets)
  - matplotlib
  - seaborn
  - tqdm
  - jupyter
  - ipykernel
  - pip
  - pip:
    - tensorboard
    - wandb  # For experiment tracking
    - thop  # For FLOPs calculation
    - pynvml  # For GPU monitoring
